//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TIN_Project.Client.Resources.AddMovie {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class AddMovie {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AddMovie() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TIN_Project.Client.Resources.AddMovie.AddMovie", typeof(AddMovie).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Movie.
        /// </summary>
        internal static string Add_Movie {
            get {
                return ResourceManager.GetString("Add Movie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description in English.
        /// </summary>
        internal static string DescriptionEN {
            get {
                return ResourceManager.GetString("DescriptionEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description in Polish.
        /// </summary>
        internal static string DescriptionPL {
            get {
                return ResourceManager.GetString("DescriptionPL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t add movie, try again.
        /// </summary>
        internal static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genres.
        /// </summary>
        internal static string Genres {
            get {
                return ResourceManager.GetString("Genres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poster URL.
        /// </summary>
        internal static string Poster_URL {
            get {
                return ResourceManager.GetString("Poster URL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title in English.
        /// </summary>
        internal static string TitleEN {
            get {
                return ResourceManager.GetString("TitleEN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title in Polish.
        /// </summary>
        internal static string TitlePL {
            get {
                return ResourceManager.GetString("TitlePL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trailer URL.
        /// </summary>
        internal static string Trailer_URL {
            get {
                return ResourceManager.GetString("Trailer URL", resourceCulture);
            }
        }
    }
}
