//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TIN_Project.Client.Resources.MovieDetails {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MovieDetails {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MovieDetails() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TIN_Project.Client.Resources.MovieDetails.MovieDetails", typeof(MovieDetails).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Book ticket.
        /// </summary>
        internal static string Book_ticket {
            get {
                return ResourceManager.GetString("Book ticket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy ticket.
        /// </summary>
        internal static string Buy_ticket {
            get {
                return ResourceManager.GetString("Buy ticket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cinema address :.
        /// </summary>
        internal static string Cinema_address {
            get {
                return ResourceManager.GetString("Cinema address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description :.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Something went wrong, try again.
        /// </summary>
        internal static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genres :.
        /// </summary>
        internal static string Genres {
            get {
                return ResourceManager.GetString("Genres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Play trailer.
        /// </summary>
        internal static string Play_trailer {
            get {
                return ResourceManager.GetString("Play trailer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have already reserved/bought ticket for this movie.
        /// </summary>
        internal static string PurchaseDenied {
            get {
                return ResourceManager.GetString("PurchaseDenied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show time :.
        /// </summary>
        internal static string Show_time {
            get {
                return ResourceManager.GetString("Show time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successful purchase.
        /// </summary>
        internal static string SuccessfulPurchase {
            get {
                return ResourceManager.GetString("SuccessfulPurchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Successful reservation.
        /// </summary>
        internal static string SuccessfulReservation {
            get {
                return ResourceManager.GetString("SuccessfulReservation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trailer.
        /// </summary>
        internal static string Trailer {
            get {
                return ResourceManager.GetString("Trailer", resourceCulture);
            }
        }
    }
}
