//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TIN_Project.Client.Resources.ManageMoviesRepertoire {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ManageMoviesRepertoire {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ManageMoviesRepertoire() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TIN_Project.Client.Resources.ManageMoviesRepertoire.ManageMoviesRepertoire", typeof(ManageMoviesRepertoire).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add movie&apos;s repertoire.
        /// </summary>
        internal static string Add_movie_s_repertoire {
            get {
                return ResourceManager.GetString("Add movie\'s repertoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t add movie&apos;s repertoire, try again.
        /// </summary>
        internal static string AddErrorMessage {
            get {
                return ResourceManager.GetString("AddErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cinema Address.
        /// </summary>
        internal static string Cinema_Address {
            get {
                return ResourceManager.GetString("Cinema Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cinema Name.
        /// </summary>
        internal static string Cinema_Name {
            get {
                return ResourceManager.GetString("Cinema Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Such movie&apos;s repertoire already exists, try again.
        /// </summary>
        internal static string ConflictErrorMessage {
            get {
                return ResourceManager.GetString("ConflictErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t delete movie&apos;s repertoire, try again.
        /// </summary>
        internal static string DeleteErrorMessage {
            get {
                return ResourceManager.GetString("DeleteErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Movies&apos; Repertoires.
        /// </summary>
        internal static string Manage_Movies__Repertoires {
            get {
                return ResourceManager.GetString("Manage Movies\' Repertoires", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Movie.
        /// </summary>
        internal static string Movie {
            get {
                return ResourceManager.GetString("Movie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No movies&apos; repertoires.
        /// </summary>
        internal static string No_movies__repertoires {
            get {
                return ResourceManager.GetString("No movies\' repertoires", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Poster.
        /// </summary>
        internal static string Poster {
            get {
                return ResourceManager.GetString("Poster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Time.
        /// </summary>
        internal static string Show_Time {
            get {
                return ResourceManager.GetString("Show Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update movie&apos;s repertoire.
        /// </summary>
        internal static string Update_movie_s_repertoire {
            get {
                return ResourceManager.GetString("Update movie\'s repertoire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t update movie&apos;s repertoire, try again.
        /// </summary>
        internal static string UpdateErrorMessage {
            get {
                return ResourceManager.GetString("UpdateErrorMessage", resourceCulture);
            }
        }
    }
}
