// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TIN_Project.Server.Context;

#nullable disable

namespace TIN_Project.Server.Migrations
{
    [DbContext(typeof(MainDbContext))]
    [Migration("20231230224923_AddedSeededDataToMovieRepertoires2")]
    partial class AddedSeededDataToMovieRepertoires2
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.14");

            modelBuilder.Entity("GenreMovie", b =>
                {
                    b.Property<int>("MoviesIdMovie")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GenresIdGenre")
                        .HasColumnType("INTEGER");

                    b.HasKey("MoviesIdMovie", "GenresIdGenre");

                    b.HasIndex("GenresIdGenre");

                    b.ToTable("GenreMovie");

                    b.HasData(
                        new
                        {
                            MoviesIdMovie = 1,
                            GenresIdGenre = 1
                        },
                        new
                        {
                            MoviesIdMovie = 1,
                            GenresIdGenre = 11
                        },
                        new
                        {
                            MoviesIdMovie = 2,
                            GenresIdGenre = 11
                        },
                        new
                        {
                            MoviesIdMovie = 2,
                            GenresIdGenre = 12
                        },
                        new
                        {
                            MoviesIdMovie = 3,
                            GenresIdGenre = 1
                        },
                        new
                        {
                            MoviesIdMovie = 3,
                            GenresIdGenre = 12
                        },
                        new
                        {
                            MoviesIdMovie = 4,
                            GenresIdGenre = 6
                        },
                        new
                        {
                            MoviesIdMovie = 5,
                            GenresIdGenre = 11
                        },
                        new
                        {
                            MoviesIdMovie = 6,
                            GenresIdGenre = 4
                        },
                        new
                        {
                            MoviesIdMovie = 6,
                            GenresIdGenre = 12
                        },
                        new
                        {
                            MoviesIdMovie = 7,
                            GenresIdGenre = 13
                        });
                });

            modelBuilder.Entity("TIN_Project.Server.Models.Cinema", b =>
                {
                    b.Property<int>("IdCinema")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("IdCinema");

                    b.ToTable("Cinemas");

                    b.HasData(
                        new
                        {
                            IdCinema = 1,
                            Address = "Złota 59, 00-120 Warszawa",
                            Name = "Multikino"
                        },
                        new
                        {
                            IdCinema = 2,
                            Address = "Wołoska 12, 02-675 Warszawa",
                            Name = "Cinema City"
                        },
                        new
                        {
                            IdCinema = 3,
                            Address = "Gen. W. Andersa 5, 00-147 Warszawa",
                            Name = "Kino Muranów"
                        },
                        new
                        {
                            IdCinema = 4,
                            Address = "Marszałkowska 28, 00-576 Warszawa",
                            Name = "Kino Luna"
                        },
                        new
                        {
                            IdCinema = 5,
                            Address = "Chmielna 33, 00-021 Warszawa",
                            Name = "Kino Atlantic"
                        },
                        new
                        {
                            IdCinema = 6,
                            Address = "Ludwika Narbutta 50A, 02-541 Warszawa",
                            Name = "Kino Iluzjon"
                        });
                });

            modelBuilder.Entity("TIN_Project.Server.Models.Genre", b =>
                {
                    b.Property<int>("IdGenre")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("IdGenre");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            IdGenre = 1,
                            Name = "Action"
                        },
                        new
                        {
                            IdGenre = 2,
                            Name = "Adventure"
                        },
                        new
                        {
                            IdGenre = 3,
                            Name = "Comedy"
                        },
                        new
                        {
                            IdGenre = 4,
                            Name = "Crime"
                        },
                        new
                        {
                            IdGenre = 5,
                            Name = "Drama"
                        },
                        new
                        {
                            IdGenre = 6,
                            Name = "Fantasy"
                        },
                        new
                        {
                            IdGenre = 7,
                            Name = "Historical"
                        },
                        new
                        {
                            IdGenre = 8,
                            Name = "Horror"
                        },
                        new
                        {
                            IdGenre = 9,
                            Name = "Mystery"
                        },
                        new
                        {
                            IdGenre = 10,
                            Name = "Romance"
                        },
                        new
                        {
                            IdGenre = 11,
                            Name = "Science Fiction"
                        },
                        new
                        {
                            IdGenre = 12,
                            Name = "Thriller"
                        },
                        new
                        {
                            IdGenre = 13,
                            Name = "Western"
                        });
                });

            modelBuilder.Entity("TIN_Project.Server.Models.Movie", b =>
                {
                    b.Property<int>("IdMovie")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("PosterUrl")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("TrailerUrl")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("IdMovie");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            IdMovie = 1,
                            Description = "A team of superheroes save the world from a powerful threat.",
                            PosterUrl = "https://www.themoviedb.org/t/p/w1280/ugX4WZJO3jEvTOerctAWJLinujo.jpg",
                            Title = "The Avengers",
                            TrailerUrl = "https://www.youtube.com/watch?v=eOrNdBpGMv8"
                        },
                        new
                        {
                            IdMovie = 2,
                            Description = "A thief enters people's dreams to steal information.",
                            PosterUrl = "https://www.themoviedb.org/t/p/original/aSY6QhgEeUYky0TMfAXjvRJj5bL.jpg",
                            Title = "Inception",
                            TrailerUrl = "https://www.youtube.com/watch?v=YoHD9XEInc0"
                        },
                        new
                        {
                            IdMovie = 3,
                            Description = "A vigilante fights crime in Gotham City.",
                            PosterUrl = "https://www.themoviedb.org/t/p/original/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
                            Title = "The Dark Knight",
                            TrailerUrl = "https://www.youtube.com/watch?v=EXeTwQWrcwY"
                        },
                        new
                        {
                            IdMovie = 4,
                            Description = "A hobbit embarks on a journey to destroy a powerful ring.",
                            PosterUrl = "https://www.themoviedb.org/t/p/original/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg",
                            Title = "The Lord of the Rings: The Fellowship of the Ring",
                            TrailerUrl = "https://www.youtube.com/watch?v=V75dMMIW2B4"
                        },
                        new
                        {
                            IdMovie = 5,
                            Description = "A hacker discovers that the world is a simulation.",
                            PosterUrl = "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/qK76PKQLd6zlMn0u83Ej9YQOqPL.jpg",
                            Title = "The Matrix",
                            TrailerUrl = "https://www.youtube.com/watch?v=m8e-FF8MsqU"
                        },
                        new
                        {
                            IdMovie = 6,
                            Description = "Various interconnected stories of criminals, lowlifes, and a mysterious briefcase.",
                            PosterUrl = "https://www.themoviedb.org/t/p/w1280/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg",
                            Title = "Pulp Fiction",
                            TrailerUrl = "https://www.youtube.com/watch?v=s7EdQ4FqbhY"
                        },
                        new
                        {
                            IdMovie = 7,
                            Description = "A freed slave sets out to rescue his wife from a brutal Mississippi plantation owner.",
                            PosterUrl = "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/6UjfRbaSdpNeaJvLIPTdhCO6yzJ.jpg",
                            Title = "Django Unchained",
                            TrailerUrl = "https://www.youtube.com/watch?v=_iH0UBYDI4g"
                        });
                });

            modelBuilder.Entity("TIN_Project.Server.Models.MovieRepertoire", b =>
                {
                    b.Property<int>("IdMovieRepertoire")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdMovie")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdRepertoire")
                        .HasColumnType("INTEGER");

                    b.Property<TimeOnly>("ShowTime")
                        .HasColumnType("TEXT");

                    b.HasKey("IdMovieRepertoire");

                    b.HasIndex("IdMovie");

                    b.HasIndex("IdRepertoire");

                    b.ToTable("MovieRepertoires");

                    b.HasData(
                        new
                        {
                            IdMovieRepertoire = 1,
                            IdMovie = 1,
                            IdRepertoire = 1,
                            ShowTime = new TimeOnly(0, 49, 23, 203).Add(TimeSpan.FromTicks(7754))
                        },
                        new
                        {
                            IdMovieRepertoire = 2,
                            IdMovie = 2,
                            IdRepertoire = 1,
                            ShowTime = new TimeOnly(1, 49, 23, 203).Add(TimeSpan.FromTicks(7823))
                        },
                        new
                        {
                            IdMovieRepertoire = 3,
                            IdMovie = 3,
                            IdRepertoire = 1,
                            ShowTime = new TimeOnly(2, 49, 23, 203).Add(TimeSpan.FromTicks(7826))
                        },
                        new
                        {
                            IdMovieRepertoire = 4,
                            IdMovie = 4,
                            IdRepertoire = 1,
                            ShowTime = new TimeOnly(3, 49, 23, 203).Add(TimeSpan.FromTicks(7828))
                        },
                        new
                        {
                            IdMovieRepertoire = 5,
                            IdMovie = 5,
                            IdRepertoire = 2,
                            ShowTime = new TimeOnly(0, 49, 23, 203).Add(TimeSpan.FromTicks(7831))
                        },
                        new
                        {
                            IdMovieRepertoire = 6,
                            IdMovie = 6,
                            IdRepertoire = 2,
                            ShowTime = new TimeOnly(1, 49, 23, 203).Add(TimeSpan.FromTicks(7833))
                        },
                        new
                        {
                            IdMovieRepertoire = 7,
                            IdMovie = 7,
                            IdRepertoire = 2,
                            ShowTime = new TimeOnly(2, 49, 23, 203).Add(TimeSpan.FromTicks(7835))
                        },
                        new
                        {
                            IdMovieRepertoire = 8,
                            IdMovie = 1,
                            IdRepertoire = 2,
                            ShowTime = new TimeOnly(3, 49, 23, 203).Add(TimeSpan.FromTicks(7839))
                        },
                        new
                        {
                            IdMovieRepertoire = 9,
                            IdMovie = 2,
                            IdRepertoire = 3,
                            ShowTime = new TimeOnly(0, 49, 23, 203).Add(TimeSpan.FromTicks(7841))
                        },
                        new
                        {
                            IdMovieRepertoire = 10,
                            IdMovie = 3,
                            IdRepertoire = 3,
                            ShowTime = new TimeOnly(1, 49, 23, 203).Add(TimeSpan.FromTicks(7843))
                        },
                        new
                        {
                            IdMovieRepertoire = 11,
                            IdMovie = 4,
                            IdRepertoire = 3,
                            ShowTime = new TimeOnly(2, 49, 23, 203).Add(TimeSpan.FromTicks(7845))
                        },
                        new
                        {
                            IdMovieRepertoire = 12,
                            IdMovie = 5,
                            IdRepertoire = 3,
                            ShowTime = new TimeOnly(3, 49, 23, 203).Add(TimeSpan.FromTicks(7848))
                        },
                        new
                        {
                            IdMovieRepertoire = 13,
                            IdMovie = 6,
                            IdRepertoire = 4,
                            ShowTime = new TimeOnly(0, 49, 23, 203).Add(TimeSpan.FromTicks(7850))
                        },
                        new
                        {
                            IdMovieRepertoire = 14,
                            IdMovie = 7,
                            IdRepertoire = 4,
                            ShowTime = new TimeOnly(1, 49, 23, 203).Add(TimeSpan.FromTicks(7852))
                        },
                        new
                        {
                            IdMovieRepertoire = 15,
                            IdMovie = 1,
                            IdRepertoire = 4,
                            ShowTime = new TimeOnly(2, 49, 23, 203).Add(TimeSpan.FromTicks(7855))
                        },
                        new
                        {
                            IdMovieRepertoire = 16,
                            IdMovie = 2,
                            IdRepertoire = 4,
                            ShowTime = new TimeOnly(3, 49, 23, 203).Add(TimeSpan.FromTicks(7893))
                        },
                        new
                        {
                            IdMovieRepertoire = 17,
                            IdMovie = 3,
                            IdRepertoire = 5,
                            ShowTime = new TimeOnly(0, 49, 23, 203).Add(TimeSpan.FromTicks(7896))
                        },
                        new
                        {
                            IdMovieRepertoire = 18,
                            IdMovie = 4,
                            IdRepertoire = 5,
                            ShowTime = new TimeOnly(1, 49, 23, 203).Add(TimeSpan.FromTicks(7898))
                        },
                        new
                        {
                            IdMovieRepertoire = 19,
                            IdMovie = 5,
                            IdRepertoire = 5,
                            ShowTime = new TimeOnly(2, 49, 23, 203).Add(TimeSpan.FromTicks(7901))
                        },
                        new
                        {
                            IdMovieRepertoire = 20,
                            IdMovie = 6,
                            IdRepertoire = 5,
                            ShowTime = new TimeOnly(3, 49, 23, 203).Add(TimeSpan.FromTicks(7903))
                        },
                        new
                        {
                            IdMovieRepertoire = 21,
                            IdMovie = 7,
                            IdRepertoire = 6,
                            ShowTime = new TimeOnly(0, 49, 23, 203).Add(TimeSpan.FromTicks(7905))
                        },
                        new
                        {
                            IdMovieRepertoire = 22,
                            IdMovie = 1,
                            IdRepertoire = 6,
                            ShowTime = new TimeOnly(1, 49, 23, 203).Add(TimeSpan.FromTicks(7907))
                        },
                        new
                        {
                            IdMovieRepertoire = 23,
                            IdMovie = 2,
                            IdRepertoire = 6,
                            ShowTime = new TimeOnly(2, 49, 23, 203).Add(TimeSpan.FromTicks(7910))
                        },
                        new
                        {
                            IdMovieRepertoire = 24,
                            IdMovie = 3,
                            IdRepertoire = 6,
                            ShowTime = new TimeOnly(3, 49, 23, 203).Add(TimeSpan.FromTicks(7912))
                        },
                        new
                        {
                            IdMovieRepertoire = 25,
                            IdMovie = 4,
                            IdRepertoire = 7,
                            ShowTime = new TimeOnly(0, 49, 23, 203).Add(TimeSpan.FromTicks(7914))
                        },
                        new
                        {
                            IdMovieRepertoire = 26,
                            IdMovie = 5,
                            IdRepertoire = 7,
                            ShowTime = new TimeOnly(1, 49, 23, 203).Add(TimeSpan.FromTicks(7917))
                        },
                        new
                        {
                            IdMovieRepertoire = 27,
                            IdMovie = 6,
                            IdRepertoire = 7,
                            ShowTime = new TimeOnly(2, 49, 23, 203).Add(TimeSpan.FromTicks(7919))
                        },
                        new
                        {
                            IdMovieRepertoire = 28,
                            IdMovie = 7,
                            IdRepertoire = 7,
                            ShowTime = new TimeOnly(3, 49, 23, 203).Add(TimeSpan.FromTicks(7922))
                        },
                        new
                        {
                            IdMovieRepertoire = 29,
                            IdMovie = 1,
                            IdRepertoire = 8,
                            ShowTime = new TimeOnly(0, 49, 23, 203).Add(TimeSpan.FromTicks(7924))
                        },
                        new
                        {
                            IdMovieRepertoire = 30,
                            IdMovie = 2,
                            IdRepertoire = 8,
                            ShowTime = new TimeOnly(1, 49, 23, 203).Add(TimeSpan.FromTicks(7926))
                        },
                        new
                        {
                            IdMovieRepertoire = 31,
                            IdMovie = 3,
                            IdRepertoire = 8,
                            ShowTime = new TimeOnly(2, 49, 23, 203).Add(TimeSpan.FromTicks(7928))
                        },
                        new
                        {
                            IdMovieRepertoire = 32,
                            IdMovie = 4,
                            IdRepertoire = 8,
                            ShowTime = new TimeOnly(3, 49, 23, 203).Add(TimeSpan.FromTicks(7931))
                        },
                        new
                        {
                            IdMovieRepertoire = 33,
                            IdMovie = 5,
                            IdRepertoire = 9,
                            ShowTime = new TimeOnly(0, 49, 23, 203).Add(TimeSpan.FromTicks(7933))
                        },
                        new
                        {
                            IdMovieRepertoire = 34,
                            IdMovie = 6,
                            IdRepertoire = 9,
                            ShowTime = new TimeOnly(1, 49, 23, 203).Add(TimeSpan.FromTicks(7935))
                        },
                        new
                        {
                            IdMovieRepertoire = 35,
                            IdMovie = 7,
                            IdRepertoire = 9,
                            ShowTime = new TimeOnly(2, 49, 23, 203).Add(TimeSpan.FromTicks(7937))
                        },
                        new
                        {
                            IdMovieRepertoire = 36,
                            IdMovie = 1,
                            IdRepertoire = 9,
                            ShowTime = new TimeOnly(3, 49, 23, 203).Add(TimeSpan.FromTicks(7940))
                        },
                        new
                        {
                            IdMovieRepertoire = 37,
                            IdMovie = 2,
                            IdRepertoire = 10,
                            ShowTime = new TimeOnly(0, 49, 23, 203).Add(TimeSpan.FromTicks(7942))
                        },
                        new
                        {
                            IdMovieRepertoire = 38,
                            IdMovie = 3,
                            IdRepertoire = 10,
                            ShowTime = new TimeOnly(1, 49, 23, 203).Add(TimeSpan.FromTicks(7944))
                        },
                        new
                        {
                            IdMovieRepertoire = 39,
                            IdMovie = 4,
                            IdRepertoire = 10,
                            ShowTime = new TimeOnly(2, 49, 23, 203).Add(TimeSpan.FromTicks(7946))
                        },
                        new
                        {
                            IdMovieRepertoire = 40,
                            IdMovie = 5,
                            IdRepertoire = 10,
                            ShowTime = new TimeOnly(3, 49, 23, 203).Add(TimeSpan.FromTicks(7949))
                        },
                        new
                        {
                            IdMovieRepertoire = 41,
                            IdMovie = 6,
                            IdRepertoire = 11,
                            ShowTime = new TimeOnly(0, 49, 23, 203).Add(TimeSpan.FromTicks(7951))
                        },
                        new
                        {
                            IdMovieRepertoire = 42,
                            IdMovie = 7,
                            IdRepertoire = 11,
                            ShowTime = new TimeOnly(1, 49, 23, 203).Add(TimeSpan.FromTicks(7953))
                        });
                });

            modelBuilder.Entity("TIN_Project.Server.Models.Order", b =>
                {
                    b.Property<int>("IdUser")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdMovieRepertoire")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdUser", "IdMovieRepertoire");

                    b.HasIndex("IdMovieRepertoire");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("TIN_Project.Server.Models.Repertoire", b =>
                {
                    b.Property<int>("IdRepertoire")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdCinema")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdRepertoire");

                    b.HasIndex("IdCinema");

                    b.ToTable("Repertoires");

                    b.HasData(
                        new
                        {
                            IdRepertoire = 1,
                            Date = new DateOnly(2023, 12, 31),
                            IdCinema = 1
                        },
                        new
                        {
                            IdRepertoire = 2,
                            Date = new DateOnly(2024, 1, 1),
                            IdCinema = 1
                        },
                        new
                        {
                            IdRepertoire = 3,
                            Date = new DateOnly(2024, 1, 2),
                            IdCinema = 1
                        },
                        new
                        {
                            IdRepertoire = 4,
                            Date = new DateOnly(2024, 1, 3),
                            IdCinema = 1
                        },
                        new
                        {
                            IdRepertoire = 5,
                            Date = new DateOnly(2024, 1, 4),
                            IdCinema = 1
                        },
                        new
                        {
                            IdRepertoire = 6,
                            Date = new DateOnly(2023, 12, 31),
                            IdCinema = 2
                        },
                        new
                        {
                            IdRepertoire = 7,
                            Date = new DateOnly(2024, 1, 1),
                            IdCinema = 2
                        },
                        new
                        {
                            IdRepertoire = 8,
                            Date = new DateOnly(2024, 1, 2),
                            IdCinema = 2
                        },
                        new
                        {
                            IdRepertoire = 9,
                            Date = new DateOnly(2024, 1, 3),
                            IdCinema = 2
                        },
                        new
                        {
                            IdRepertoire = 10,
                            Date = new DateOnly(2024, 1, 4),
                            IdCinema = 2
                        },
                        new
                        {
                            IdRepertoire = 11,
                            Date = new DateOnly(2023, 12, 31),
                            IdCinema = 3
                        },
                        new
                        {
                            IdRepertoire = 12,
                            Date = new DateOnly(2024, 1, 1),
                            IdCinema = 3
                        },
                        new
                        {
                            IdRepertoire = 13,
                            Date = new DateOnly(2024, 1, 2),
                            IdCinema = 3
                        },
                        new
                        {
                            IdRepertoire = 14,
                            Date = new DateOnly(2024, 1, 3),
                            IdCinema = 3
                        },
                        new
                        {
                            IdRepertoire = 15,
                            Date = new DateOnly(2024, 1, 4),
                            IdCinema = 3
                        },
                        new
                        {
                            IdRepertoire = 16,
                            Date = new DateOnly(2023, 12, 31),
                            IdCinema = 4
                        },
                        new
                        {
                            IdRepertoire = 17,
                            Date = new DateOnly(2024, 1, 1),
                            IdCinema = 4
                        },
                        new
                        {
                            IdRepertoire = 18,
                            Date = new DateOnly(2024, 1, 2),
                            IdCinema = 4
                        },
                        new
                        {
                            IdRepertoire = 19,
                            Date = new DateOnly(2024, 1, 3),
                            IdCinema = 4
                        },
                        new
                        {
                            IdRepertoire = 20,
                            Date = new DateOnly(2024, 1, 4),
                            IdCinema = 4
                        },
                        new
                        {
                            IdRepertoire = 21,
                            Date = new DateOnly(2023, 12, 31),
                            IdCinema = 5
                        },
                        new
                        {
                            IdRepertoire = 22,
                            Date = new DateOnly(2024, 1, 1),
                            IdCinema = 5
                        },
                        new
                        {
                            IdRepertoire = 23,
                            Date = new DateOnly(2024, 1, 2),
                            IdCinema = 5
                        },
                        new
                        {
                            IdRepertoire = 24,
                            Date = new DateOnly(2024, 1, 3),
                            IdCinema = 5
                        },
                        new
                        {
                            IdRepertoire = 25,
                            Date = new DateOnly(2024, 1, 4),
                            IdCinema = 5
                        },
                        new
                        {
                            IdRepertoire = 26,
                            Date = new DateOnly(2023, 12, 31),
                            IdCinema = 6
                        },
                        new
                        {
                            IdRepertoire = 27,
                            Date = new DateOnly(2024, 1, 1),
                            IdCinema = 6
                        },
                        new
                        {
                            IdRepertoire = 28,
                            Date = new DateOnly(2024, 1, 2),
                            IdCinema = 6
                        },
                        new
                        {
                            IdRepertoire = 29,
                            Date = new DateOnly(2024, 1, 3),
                            IdCinema = 6
                        },
                        new
                        {
                            IdRepertoire = 30,
                            Date = new DateOnly(2024, 1, 4),
                            IdCinema = 6
                        });
                });

            modelBuilder.Entity("TIN_Project.Server.Models.User", b =>
                {
                    b.Property<int>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RefreshTokenExpirationDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("IdUser");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            IdUser = 1,
                            BirthDate = new DateOnly(1999, 1, 1),
                            Email = "wowowow",
                            Name = "John",
                            Password = "password",
                            Role = 1,
                            Surname = "Doe",
                            Username = "username"
                        });
                });

            modelBuilder.Entity("GenreMovie", b =>
                {
                    b.HasOne("TIN_Project.Server.Models.Genre", null)
                        .WithMany()
                        .HasForeignKey("GenresIdGenre")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TIN_Project.Server.Models.Movie", null)
                        .WithMany()
                        .HasForeignKey("MoviesIdMovie")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TIN_Project.Server.Models.MovieRepertoire", b =>
                {
                    b.HasOne("TIN_Project.Server.Models.Movie", "Movie")
                        .WithMany("MovieRepertoires")
                        .HasForeignKey("IdMovie")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TIN_Project.Server.Models.Repertoire", "Repertoire")
                        .WithMany("MovieRepertoires")
                        .HasForeignKey("IdRepertoire")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("Repertoire");
                });

            modelBuilder.Entity("TIN_Project.Server.Models.Order", b =>
                {
                    b.HasOne("TIN_Project.Server.Models.MovieRepertoire", "MovieRepertoire")
                        .WithMany("Orders")
                        .HasForeignKey("IdMovieRepertoire")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TIN_Project.Server.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MovieRepertoire");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TIN_Project.Server.Models.Repertoire", b =>
                {
                    b.HasOne("TIN_Project.Server.Models.Cinema", "Cinema")
                        .WithMany("Repertoires")
                        .HasForeignKey("IdCinema")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cinema");
                });

            modelBuilder.Entity("TIN_Project.Server.Models.Cinema", b =>
                {
                    b.Navigation("Repertoires");
                });

            modelBuilder.Entity("TIN_Project.Server.Models.Movie", b =>
                {
                    b.Navigation("MovieRepertoires");
                });

            modelBuilder.Entity("TIN_Project.Server.Models.MovieRepertoire", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("TIN_Project.Server.Models.Repertoire", b =>
                {
                    b.Navigation("MovieRepertoires");
                });

            modelBuilder.Entity("TIN_Project.Server.Models.User", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
