// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TIN_Project.Server.Context;

#nullable disable

namespace TIN_Project.Server.Migrations
{
    [DbContext(typeof(MainDbContext))]
    [Migration("20240114152434_AddedMoreSeededData")]
    partial class AddedMoreSeededData
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.14");

            modelBuilder.Entity("GenreMovie", b =>
                {
                    b.Property<int>("MoviesIdMovie")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GenresIdGenre")
                        .HasColumnType("INTEGER");

                    b.HasKey("MoviesIdMovie", "GenresIdGenre");

                    b.HasIndex("GenresIdGenre");

                    b.ToTable("GenreMovie");

                    b.HasData(
                        new
                        {
                            MoviesIdMovie = 1,
                            GenresIdGenre = 1
                        },
                        new
                        {
                            MoviesIdMovie = 1,
                            GenresIdGenre = 11
                        },
                        new
                        {
                            MoviesIdMovie = 2,
                            GenresIdGenre = 11
                        },
                        new
                        {
                            MoviesIdMovie = 2,
                            GenresIdGenre = 12
                        },
                        new
                        {
                            MoviesIdMovie = 3,
                            GenresIdGenre = 1
                        },
                        new
                        {
                            MoviesIdMovie = 3,
                            GenresIdGenre = 12
                        },
                        new
                        {
                            MoviesIdMovie = 4,
                            GenresIdGenre = 6
                        },
                        new
                        {
                            MoviesIdMovie = 5,
                            GenresIdGenre = 11
                        },
                        new
                        {
                            MoviesIdMovie = 6,
                            GenresIdGenre = 4
                        },
                        new
                        {
                            MoviesIdMovie = 6,
                            GenresIdGenre = 12
                        },
                        new
                        {
                            MoviesIdMovie = 7,
                            GenresIdGenre = 13
                        },
                        new
                        {
                            MoviesIdMovie = 8,
                            GenresIdGenre = 4
                        },
                        new
                        {
                            MoviesIdMovie = 8,
                            GenresIdGenre = 5
                        },
                        new
                        {
                            MoviesIdMovie = 9,
                            GenresIdGenre = 4
                        },
                        new
                        {
                            MoviesIdMovie = 9,
                            GenresIdGenre = 5
                        },
                        new
                        {
                            MoviesIdMovie = 10,
                            GenresIdGenre = 4
                        },
                        new
                        {
                            MoviesIdMovie = 10,
                            GenresIdGenre = 5
                        },
                        new
                        {
                            MoviesIdMovie = 11,
                            GenresIdGenre = 11
                        },
                        new
                        {
                            MoviesIdMovie = 12,
                            GenresIdGenre = 2
                        },
                        new
                        {
                            MoviesIdMovie = 12,
                            GenresIdGenre = 11
                        },
                        new
                        {
                            MoviesIdMovie = 13,
                            GenresIdGenre = 2
                        },
                        new
                        {
                            MoviesIdMovie = 13,
                            GenresIdGenre = 11
                        },
                        new
                        {
                            MoviesIdMovie = 14,
                            GenresIdGenre = 2
                        },
                        new
                        {
                            MoviesIdMovie = 14,
                            GenresIdGenre = 11
                        },
                        new
                        {
                            MoviesIdMovie = 15,
                            GenresIdGenre = 2
                        },
                        new
                        {
                            MoviesIdMovie = 15,
                            GenresIdGenre = 11
                        },
                        new
                        {
                            MoviesIdMovie = 16,
                            GenresIdGenre = 2
                        },
                        new
                        {
                            MoviesIdMovie = 16,
                            GenresIdGenre = 6
                        },
                        new
                        {
                            MoviesIdMovie = 17,
                            GenresIdGenre = 2
                        },
                        new
                        {
                            MoviesIdMovie = 17,
                            GenresIdGenre = 6
                        },
                        new
                        {
                            MoviesIdMovie = 18,
                            GenresIdGenre = 4
                        },
                        new
                        {
                            MoviesIdMovie = 18,
                            GenresIdGenre = 12
                        },
                        new
                        {
                            MoviesIdMovie = 19,
                            GenresIdGenre = 4
                        },
                        new
                        {
                            MoviesIdMovie = 19,
                            GenresIdGenre = 12
                        },
                        new
                        {
                            MoviesIdMovie = 20,
                            GenresIdGenre = 5
                        });
                });

            modelBuilder.Entity("TIN_Project.Server.Models.Cinema", b =>
                {
                    b.Property<int>("IdCinema")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.HasKey("IdCinema");

                    b.ToTable("Cinemas");

                    b.HasData(
                        new
                        {
                            IdCinema = 1,
                            Address = "Złota 59, 00-120 Warszawa",
                            Name = "Multikino"
                        },
                        new
                        {
                            IdCinema = 2,
                            Address = "Wołoska 12, 02-675 Warszawa",
                            Name = "Cinema City"
                        },
                        new
                        {
                            IdCinema = 3,
                            Address = "Gen. W. Andersa 5, 00-147 Warszawa",
                            Name = "Kino Muranów"
                        },
                        new
                        {
                            IdCinema = 4,
                            Address = "Marszałkowska 28, 00-576 Warszawa",
                            Name = "Kino Luna"
                        },
                        new
                        {
                            IdCinema = 5,
                            Address = "Chmielna 33, 00-021 Warszawa",
                            Name = "Kino Atlantic"
                        },
                        new
                        {
                            IdCinema = 6,
                            Address = "Ludwika Narbutta 50A, 02-541 Warszawa",
                            Name = "Kino Iluzjon"
                        });
                });

            modelBuilder.Entity("TIN_Project.Server.Models.Genre", b =>
                {
                    b.Property<int>("IdGenre")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EnglishName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("PolishName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("IdGenre");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            IdGenre = 1,
                            EnglishName = "Action",
                            PolishName = "Akcja"
                        },
                        new
                        {
                            IdGenre = 2,
                            EnglishName = "Adventure",
                            PolishName = "Przygodowy"
                        },
                        new
                        {
                            IdGenre = 3,
                            EnglishName = "Comedy",
                            PolishName = "Komedia"
                        },
                        new
                        {
                            IdGenre = 4,
                            EnglishName = "Crime",
                            PolishName = "Kryminalny"
                        },
                        new
                        {
                            IdGenre = 5,
                            EnglishName = "Drama",
                            PolishName = "Dramat"
                        },
                        new
                        {
                            IdGenre = 6,
                            EnglishName = "Fantasy",
                            PolishName = "Fantasy"
                        },
                        new
                        {
                            IdGenre = 7,
                            EnglishName = "Historical",
                            PolishName = "Historyczny"
                        },
                        new
                        {
                            IdGenre = 8,
                            EnglishName = "Horror",
                            PolishName = "Horror"
                        },
                        new
                        {
                            IdGenre = 9,
                            EnglishName = "Mystery",
                            PolishName = "Tajemnica"
                        },
                        new
                        {
                            IdGenre = 10,
                            EnglishName = "Romance",
                            PolishName = "Romans"
                        },
                        new
                        {
                            IdGenre = 11,
                            EnglishName = "Science Fiction",
                            PolishName = "Science Fiction"
                        },
                        new
                        {
                            IdGenre = 12,
                            EnglishName = "Thriller",
                            PolishName = "Thriller"
                        },
                        new
                        {
                            IdGenre = 13,
                            EnglishName = "Western",
                            PolishName = "Western"
                        });
                });

            modelBuilder.Entity("TIN_Project.Server.Models.Movie", b =>
                {
                    b.Property<int>("IdMovie")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("EnglishDescription")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("EnglishTitle")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("PolishDescription")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("TEXT");

                    b.Property<string>("PolishTitle")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("TEXT");

                    b.Property<string>("PosterUrl")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("TrailerUrl")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("IdMovie");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            IdMovie = 1,
                            EnglishDescription = "A team of superheroes save the world from a powerful threat.",
                            EnglishTitle = "The Avengers",
                            PolishDescription = "Zespół superbohaterów ratuje świat przed potężnym zagrożeniem.",
                            PolishTitle = "Avengers",
                            PosterUrl = "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/RYMX2wcKCBAr24UyPD7xwmjaTn.jpg",
                            TrailerUrl = "https://www.youtube.com/watch?v=eOrNdBpGMv8"
                        },
                        new
                        {
                            IdMovie = 2,
                            EnglishDescription = "A thief enters people's dreams to steal information.",
                            EnglishTitle = "Inception",
                            PolishDescription = "Złodziej wkracza do snów ludzi, aby ukraść informacje.",
                            PolishTitle = "Incepcja",
                            PosterUrl = "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg",
                            TrailerUrl = "https://www.youtube.com/watch?v=YoHD9XEInc0"
                        },
                        new
                        {
                            IdMovie = 3,
                            EnglishDescription = "A vigilante fights crime in Gotham City.",
                            EnglishTitle = "The Dark Knight",
                            PolishDescription = "Samozwańczy sprawiedliwy walczy ze złem w Gotham City.",
                            PolishTitle = "Mroczny Rycerz",
                            PosterUrl = "https://www.themoviedb.org/t/p/original/qJ2tW6WMUDux911r6m7haRef0WH.jpg",
                            TrailerUrl = "https://www.youtube.com/watch?v=EXeTwQWrcwY"
                        },
                        new
                        {
                            IdMovie = 4,
                            EnglishDescription = "A hobbit embarks on a journey to destroy a powerful ring.",
                            EnglishTitle = "The Lord of the Rings: The Fellowship of the Ring",
                            PolishDescription = "Hobbit wyrusza w podróż, aby zniszczyć potężny pierścień.",
                            PolishTitle = "Władca Pierścieni: Drużyna Pierścienia",
                            PosterUrl = "https://www.themoviedb.org/t/p/original/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg",
                            TrailerUrl = "https://www.youtube.com/watch?v=V75dMMIW2B4"
                        },
                        new
                        {
                            IdMovie = 5,
                            EnglishDescription = "A hacker discovers that the world is a simulation.",
                            EnglishTitle = "The Matrix",
                            PolishDescription = "Haker odkrywa, że świat jest symulacją.",
                            PolishTitle = "Matrix",
                            PosterUrl = "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/qK76PKQLd6zlMn0u83Ej9YQOqPL.jpg",
                            TrailerUrl = "https://www.youtube.com/watch?v=m8e-FF8MsqU"
                        },
                        new
                        {
                            IdMovie = 6,
                            EnglishDescription = "Various interconnected stories of criminals, lowlifes, and a mysterious briefcase.",
                            EnglishTitle = "Pulp Fiction",
                            PolishDescription = "Różne powiązane ze sobą historie kryminalistów, łotrów i tajemniczej walizki.",
                            PolishTitle = "Pulp Fiction",
                            PosterUrl = "https://www.themoviedb.org/t/p/w1280/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg",
                            TrailerUrl = "https://www.youtube.com/watch?v=s7EdQ4FqbhY"
                        },
                        new
                        {
                            IdMovie = 7,
                            EnglishDescription = "A freed slave sets out to rescue his wife from a brutal Mississippi plantation owner.",
                            EnglishTitle = "Django Unchained",
                            PolishDescription = "Uwolniony niewolnik wyrusza, aby uratować swoją żonę przed brutalnym właścicielem plantacji w Missisipi.",
                            PolishTitle = "Django",
                            PosterUrl = "https://www.themoviedb.org/t/p/w600_and_h900_bestv2/6UjfRbaSdpNeaJvLIPTdhCO6yzJ.jpg",
                            TrailerUrl = "https://www.youtube.com/watch?v=_iH0UBYDI4g"
                        },
                        new
                        {
                            IdMovie = 8,
                            EnglishDescription = "Framed in the 1940s for the double murder of his wife and her lover, upstanding banker Andy Dufresne begins a new life at the Shawshank prison, where he puts his accounting skills to work for an amoral warden. During his long stretch in prison, Dufresne comes to be admired by the other inmates -- including an older prisoner named Red -- for his integrity and unquenchable sense of hope.",
                            EnglishTitle = "The Shawshank Redemption",
                            PolishDescription = "Andy Dufresne jest młodym, obiecującym bankierem. Jego życie zmienia się drastycznie, kiedy zostaje niesłusznie oskarżony o zamordowanie swojej żony i jej kochanka. Skazany na dożywocie, trafia do więzienia Shawshank, gdzie rządy sprawują sadystyczni strażnicy oraz dyrektor hipokryta i oszust. Andy żeby przeżyć lata, jakie przyjdzie mu spędzić w celi, Andy będzie musiał wykazać się sprytem i wolą przetrwania.",
                            PolishTitle = "Skazani na Shawshank",
                            PosterUrl = "https://www.themoviedb.org/t/p/w1280/sBnhJ4f5KAzg6C3FwnEb8QFj8SB.jpg",
                            TrailerUrl = "https://www.youtube.com/watch?v=NmzuHjWmXOc&ab_channel=RottenTomatoesClassicTrailers"
                        },
                        new
                        {
                            IdMovie = 9,
                            EnglishDescription = "An organized crime dynasty's aging patriarch transfers control of his clandestine empire to his reluctant son.",
                            EnglishTitle = "The Godfather",
                            PolishDescription = "Starzejący się patriarcha rodu przestępczego przekazuje kontrolę nad swoim imperium swojemu synowi.",
                            PolishTitle = "Ojciec Chrzestny",
                            PosterUrl = "https://www.themoviedb.org/t/p/w1280/3bhkrj58Vtu7enYsRolD1fZdja1.jpg",
                            TrailerUrl = "https://www.youtube.com/watch?v=sY1S34973zA"
                        },
                        new
                        {
                            IdMovie = 10,
                            EnglishDescription = "The early life and career of Vito Corleone in 1920s New York City is portrayed, while his son, Michael, expands and tightens his grip on the family crime syndicate.",
                            EnglishTitle = "The Godfather: Part II",
                            PolishDescription = "Wczesne życie i kariera Vito Corleone w Nowym Jorku w latach 20. XX wieku, podczas gdy jego syn Michael rozszerza i wzmacnia swoje wpływy w rodzinnej mafii.",
                            PolishTitle = "Ojciec Chrzestny II",
                            PosterUrl = "https://www.themoviedb.org/t/p/w1280/hek3koDUyRQk7FIhPXsa6mT2Zc3.jpg",
                            TrailerUrl = "https://www.youtube.com/watch?v=9O1Iy9od7-A"
                        },
                        new
                        {
                            IdMovie = 11,
                            EnglishDescription = "A team of explorers travel through a wormhole in space in an attempt to ensure humanity's survival.",
                            EnglishTitle = "Interstellar",
                            PolishDescription = "Grupa badaczy podróżuje przez tunel czasoprzestrzenny w kosmosie, aby zapewnić przetrwanie ludzkości.",
                            PolishTitle = "Interstellar",
                            PosterUrl = "https://www.themoviedb.org/t/p/w1280/gEU2QniE6E77NI6lCU6MxlNBvIx.jpg",
                            TrailerUrl = "https://www.youtube.com/watch?v=0vxOhd4qlnA"
                        },
                        new
                        {
                            IdMovie = 12,
                            EnglishDescription = "Katniss Everdeen voluntarily takes her younger sister's place in the Hunger Games: a televised competition in which two teenagers from each of the twelve Districts of Panem are chosen at random to fight to the death.",
                            EnglishTitle = "Hunger Games",
                            PolishDescription = "Katniss Everdeen dobrowolnie bierze miejsce swojej młodszej siostry w Igrzyskach Śmierci: telewizyjnym konkursie, w którym dwóch nastolatków z każdego z dwunastu Dystryktów Panem zostaje wybranych losowo do walki na śmierć i życie.",
                            PolishTitle = "Igrzyska Śmierci",
                            PosterUrl = "https://www.themoviedb.org/t/p/w1280/yXCbOiVDCxO71zI7cuwBRXdftq8.jpg",
                            TrailerUrl = "https://www.youtube.com/watch?v=mfmrPu43DF8&ab_channel=LionsgateMovies"
                        },
                        new
                        {
                            IdMovie = 13,
                            EnglishDescription = "Katniss Everdeen and Peeta Mellark become targets of the Capitol after their victory in the 74th Hunger Games sparks a rebellion in the Districts of Panem.",
                            EnglishTitle = "The Hunger Games: Catching Fire",
                            PolishDescription = "Katniss Everdeen i Peeta Mellark stają się celem Kapitolu po tym, jak ich zwycięstwo w 74 Igrzyskach Śmierci wywołuje rebelię w Dystryktach Panem.",
                            PolishTitle = "Igrzyska Śmierci: W Pierścieniu Ognia",
                            PosterUrl = "https://www.themoviedb.org/t/p/w1280/uFQbcR7h1stMlN1d3a7RmV0luLZ.jpg",
                            TrailerUrl = "https://www.youtube.com/watch?v=EAzGXqJSDJ8"
                        },
                        new
                        {
                            IdMovie = 14,
                            EnglishDescription = "Katniss Everdeen is in District 13 after she shatters the games forever. Under the leadership of President Coin and the advice of her trusted friends, Katniss spreads her wings as she fights to save Peeta and a nation moved by her courage.",
                            EnglishTitle = "The Hunger Games: Mockingjay - Part 1",
                            PolishDescription = "Katniss Everdeen znajduje się w Dystrykcie 13 po tym, jak na zawsze zakończyła igrzyska. Pod przywództwem prezydent Coin i z radą zaufanych przyjaciół, walczy o uratowanie Peety i narodu poruszonego jej odwagą.",
                            PolishTitle = "Igrzyska Śmierci: Kosogłos. Część 1",
                            PosterUrl = "https://www.themoviedb.org/t/p/w1280/4FAA18ZIja70d1Tu5hr5cj2q1sB.jpg",
                            TrailerUrl = "https://www.youtube.com/watch?v=3PkkHsuMrho"
                        },
                        new
                        {
                            IdMovie = 15,
                            EnglishDescription = "Katniss and a team of rebels from District 13 prepare for the final battle that will decide the fate of Panem.",
                            EnglishTitle = "The Hunger Games: Mockingjay - Part 2",
                            PolishDescription = "Katniss i drużyna rebeliantów z Dystryktu 13 przygotowują się do ostatecznej bitwy, która zdecyduje o losach Panem.",
                            PolishTitle = "Igrzyska Śmierci: Kosogłos. Część 2",
                            PosterUrl = "https://www.themoviedb.org/t/p/w1280/lImKHDfExAulp16grYm8zD5eONE.jpg",
                            TrailerUrl = "https://www.youtube.com/watch?v=n-7K_OjsDCQ&ab_channel=TheHungerGames"
                        },
                        new
                        {
                            IdMovie = 16,
                            EnglishDescription = "While Frodo and Sam edge closer to Mordor with the help of the shifty Gollum, the divided fellowship makes a stand against Sauron's new ally, Saruman, and his hordes of Isengard.",
                            EnglishTitle = "The Lord of the Rings: The Two Towers",
                            PolishDescription = "Podczas gdy Frodo i Sam zbliżają się do Mordoru z pomocą przewrotnego Golluma, podzielona drużyna stawia opór nowemu sojusznikowi Saurona, Sarumanowi, i jego hordom Isengardu.",
                            PolishTitle = "Władca Pierścieni: Dwie Wieże",
                            PosterUrl = "https://www.themoviedb.org/t/p/w1280/5VTN0pR8gcqV3EPUHHfMGnJYN9L.jpg",
                            TrailerUrl = "https://www.youtube.com/watch?v=LbfMDwc4azU"
                        },
                        new
                        {
                            IdMovie = 17,
                            EnglishDescription = "Aragorn is revealed as the heir to the ancient kings as he, Gandalf and the other members of the broken fellowship struggle to save Gondor from Sauron's forces. Meanwhile, Frodo and Sam take the ring closer to the heart of Mordor, the dark lord's realm.",
                            EnglishTitle = "The Lord of the Rings: The Return of the King",
                            PolishDescription = "Aragorn walczy, aby wypełnić przepowiednię i poprowadzić swoich zwolenników przeciw rosnącej sile Władcy Ciemności Saurona, aby Powiernik Pierścienia mógł zakończyć swoją misję. Tymczasem Frodo i Sam zabierają pierścień bliżej serca Mordoru, królestwa ciemnego pana.",
                            PolishTitle = "Władca Pierścieni: Powrót Króla",
                            PosterUrl = "https://www.themoviedb.org/t/p/w1280/rCzpDGLbOoPwLjy3OAm5NUPOTrC.jpg",
                            TrailerUrl = "https://www.youtube.com/watch?v=r5X-hFf6Bwo"
                        },
                        new
                        {
                            IdMovie = 18,
                            EnglishDescription = "Two detectives, a rookie and a veteran, hunt a serial killer who uses the seven deadly sins as his motives.",
                            EnglishTitle = "Se7en",
                            PolishDescription = "Dwóch detektywów, nowicjusz i weteran, tropi seryjnego mordercę, który używa siedmiu grzechów głównych jako swoich motywów.",
                            PolishTitle = "Siedem",
                            PosterUrl = "https://www.themoviedb.org/t/p/w1280/6yoghtyTpznpBik8EngEmJskVUO.jpg",
                            TrailerUrl = "https://www.youtube.com/watch?v=J4YV2_TcCoE"
                        },
                        new
                        {
                            IdMovie = 19,
                            EnglishDescription = "A young F.B.I. cadet must receive the help of an incarcerated and manipulative cannibal killer to help catch another serial killer, a madman who skins his victims.",
                            EnglishTitle = "The Silence of the Lambs",
                            PolishDescription = "Młoda agentka F.B.I. poszukuje pomocy u uwięzionego i manipulującego kanibala zabójcy, aby złapać innego seryjnego mordercę, szaleńca, który obdziera ze skóry swoje ofiary.",
                            PolishTitle = "Milczenie Owiec",
                            PosterUrl = "https://www.themoviedb.org/t/p/w1280/uS9m8OBk1A8eM9I042bx8XXpqAq.jpg",
                            TrailerUrl = "https://www.youtube.com/watch?v=6iB21hsprAQ&ab_channel=MGM"
                        },
                        new
                        {
                            IdMovie = 20,
                            EnglishDescription = "An insomniac office worker and a devil-may-care soapmaker form an underground fight club that evolves into something much, much more.",
                            EnglishTitle = "Fight Club",
                            PolishDescription = "Bezsenni biurowi robotnicy i niefrasobliwy producent mydła tworzą podziemny klub walki, który ewoluuje w coś znacznie więcej.",
                            PolishTitle = "Podziemny Krąg",
                            PosterUrl = "https://www.themoviedb.org/t/p/w1280/pB8BM7pdSp6B6Ih7QZ4DrQ3PmJK.jpg",
                            TrailerUrl = "https://www.youtube.com/watch?v=SUXWAEX2jlg"
                        });
                });

            modelBuilder.Entity("TIN_Project.Server.Models.MovieRepertoire", b =>
                {
                    b.Property<int>("IdMovieRepertoire")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdMovie")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdRepertoire")
                        .HasColumnType("INTEGER");

                    b.Property<TimeOnly>("ShowTime")
                        .HasColumnType("TEXT");

                    b.HasKey("IdMovieRepertoire");

                    b.HasIndex("IdMovie");

                    b.HasIndex("IdRepertoire");

                    b.ToTable("MovieRepertoires");

                    b.HasData(
                        new
                        {
                            IdMovieRepertoire = 1,
                            IdMovie = 1,
                            IdRepertoire = 1,
                            ShowTime = new TimeOnly(17, 24, 34, 475).Add(TimeSpan.FromTicks(8740))
                        },
                        new
                        {
                            IdMovieRepertoire = 2,
                            IdMovie = 2,
                            IdRepertoire = 1,
                            ShowTime = new TimeOnly(18, 24, 34, 475).Add(TimeSpan.FromTicks(8808))
                        },
                        new
                        {
                            IdMovieRepertoire = 3,
                            IdMovie = 3,
                            IdRepertoire = 1,
                            ShowTime = new TimeOnly(19, 24, 34, 475).Add(TimeSpan.FromTicks(8811))
                        },
                        new
                        {
                            IdMovieRepertoire = 4,
                            IdMovie = 4,
                            IdRepertoire = 1,
                            ShowTime = new TimeOnly(20, 24, 34, 475).Add(TimeSpan.FromTicks(8813))
                        },
                        new
                        {
                            IdMovieRepertoire = 5,
                            IdMovie = 5,
                            IdRepertoire = 2,
                            ShowTime = new TimeOnly(17, 24, 34, 475).Add(TimeSpan.FromTicks(8815))
                        },
                        new
                        {
                            IdMovieRepertoire = 6,
                            IdMovie = 6,
                            IdRepertoire = 2,
                            ShowTime = new TimeOnly(18, 24, 34, 475).Add(TimeSpan.FromTicks(8817))
                        },
                        new
                        {
                            IdMovieRepertoire = 7,
                            IdMovie = 7,
                            IdRepertoire = 2,
                            ShowTime = new TimeOnly(19, 24, 34, 475).Add(TimeSpan.FromTicks(8819))
                        },
                        new
                        {
                            IdMovieRepertoire = 8,
                            IdMovie = 1,
                            IdRepertoire = 2,
                            ShowTime = new TimeOnly(20, 24, 34, 475).Add(TimeSpan.FromTicks(8821))
                        },
                        new
                        {
                            IdMovieRepertoire = 9,
                            IdMovie = 2,
                            IdRepertoire = 3,
                            ShowTime = new TimeOnly(17, 24, 34, 475).Add(TimeSpan.FromTicks(8823))
                        },
                        new
                        {
                            IdMovieRepertoire = 10,
                            IdMovie = 3,
                            IdRepertoire = 3,
                            ShowTime = new TimeOnly(18, 24, 34, 475).Add(TimeSpan.FromTicks(8825))
                        },
                        new
                        {
                            IdMovieRepertoire = 11,
                            IdMovie = 4,
                            IdRepertoire = 3,
                            ShowTime = new TimeOnly(19, 24, 34, 475).Add(TimeSpan.FromTicks(8827))
                        },
                        new
                        {
                            IdMovieRepertoire = 12,
                            IdMovie = 5,
                            IdRepertoire = 3,
                            ShowTime = new TimeOnly(20, 24, 34, 475).Add(TimeSpan.FromTicks(8829))
                        },
                        new
                        {
                            IdMovieRepertoire = 13,
                            IdMovie = 6,
                            IdRepertoire = 4,
                            ShowTime = new TimeOnly(17, 24, 34, 475).Add(TimeSpan.FromTicks(8831))
                        },
                        new
                        {
                            IdMovieRepertoire = 14,
                            IdMovie = 7,
                            IdRepertoire = 4,
                            ShowTime = new TimeOnly(18, 24, 34, 475).Add(TimeSpan.FromTicks(8833))
                        },
                        new
                        {
                            IdMovieRepertoire = 15,
                            IdMovie = 1,
                            IdRepertoire = 4,
                            ShowTime = new TimeOnly(19, 24, 34, 475).Add(TimeSpan.FromTicks(8835))
                        },
                        new
                        {
                            IdMovieRepertoire = 16,
                            IdMovie = 2,
                            IdRepertoire = 4,
                            ShowTime = new TimeOnly(20, 24, 34, 475).Add(TimeSpan.FromTicks(8836))
                        },
                        new
                        {
                            IdMovieRepertoire = 17,
                            IdMovie = 3,
                            IdRepertoire = 5,
                            ShowTime = new TimeOnly(17, 24, 34, 475).Add(TimeSpan.FromTicks(8838))
                        },
                        new
                        {
                            IdMovieRepertoire = 18,
                            IdMovie = 4,
                            IdRepertoire = 5,
                            ShowTime = new TimeOnly(18, 24, 34, 475).Add(TimeSpan.FromTicks(8840))
                        },
                        new
                        {
                            IdMovieRepertoire = 19,
                            IdMovie = 5,
                            IdRepertoire = 5,
                            ShowTime = new TimeOnly(19, 24, 34, 475).Add(TimeSpan.FromTicks(8842))
                        },
                        new
                        {
                            IdMovieRepertoire = 20,
                            IdMovie = 6,
                            IdRepertoire = 5,
                            ShowTime = new TimeOnly(20, 24, 34, 475).Add(TimeSpan.FromTicks(8844))
                        },
                        new
                        {
                            IdMovieRepertoire = 21,
                            IdMovie = 7,
                            IdRepertoire = 6,
                            ShowTime = new TimeOnly(17, 24, 34, 475).Add(TimeSpan.FromTicks(8846))
                        },
                        new
                        {
                            IdMovieRepertoire = 22,
                            IdMovie = 1,
                            IdRepertoire = 6,
                            ShowTime = new TimeOnly(18, 24, 34, 475).Add(TimeSpan.FromTicks(8848))
                        },
                        new
                        {
                            IdMovieRepertoire = 23,
                            IdMovie = 2,
                            IdRepertoire = 6,
                            ShowTime = new TimeOnly(19, 24, 34, 475).Add(TimeSpan.FromTicks(8850))
                        },
                        new
                        {
                            IdMovieRepertoire = 24,
                            IdMovie = 3,
                            IdRepertoire = 6,
                            ShowTime = new TimeOnly(20, 24, 34, 475).Add(TimeSpan.FromTicks(8852))
                        },
                        new
                        {
                            IdMovieRepertoire = 25,
                            IdMovie = 4,
                            IdRepertoire = 7,
                            ShowTime = new TimeOnly(17, 24, 34, 475).Add(TimeSpan.FromTicks(8854))
                        },
                        new
                        {
                            IdMovieRepertoire = 26,
                            IdMovie = 5,
                            IdRepertoire = 7,
                            ShowTime = new TimeOnly(18, 24, 34, 475).Add(TimeSpan.FromTicks(8856))
                        },
                        new
                        {
                            IdMovieRepertoire = 27,
                            IdMovie = 6,
                            IdRepertoire = 7,
                            ShowTime = new TimeOnly(19, 24, 34, 475).Add(TimeSpan.FromTicks(8858))
                        },
                        new
                        {
                            IdMovieRepertoire = 28,
                            IdMovie = 7,
                            IdRepertoire = 7,
                            ShowTime = new TimeOnly(20, 24, 34, 475).Add(TimeSpan.FromTicks(8860))
                        },
                        new
                        {
                            IdMovieRepertoire = 29,
                            IdMovie = 1,
                            IdRepertoire = 8,
                            ShowTime = new TimeOnly(17, 24, 34, 475).Add(TimeSpan.FromTicks(8862))
                        },
                        new
                        {
                            IdMovieRepertoire = 30,
                            IdMovie = 2,
                            IdRepertoire = 8,
                            ShowTime = new TimeOnly(18, 24, 34, 475).Add(TimeSpan.FromTicks(8864))
                        },
                        new
                        {
                            IdMovieRepertoire = 31,
                            IdMovie = 3,
                            IdRepertoire = 8,
                            ShowTime = new TimeOnly(19, 24, 34, 475).Add(TimeSpan.FromTicks(8866))
                        },
                        new
                        {
                            IdMovieRepertoire = 32,
                            IdMovie = 4,
                            IdRepertoire = 8,
                            ShowTime = new TimeOnly(20, 24, 34, 475).Add(TimeSpan.FromTicks(8868))
                        },
                        new
                        {
                            IdMovieRepertoire = 33,
                            IdMovie = 5,
                            IdRepertoire = 9,
                            ShowTime = new TimeOnly(17, 24, 34, 475).Add(TimeSpan.FromTicks(8869))
                        },
                        new
                        {
                            IdMovieRepertoire = 34,
                            IdMovie = 6,
                            IdRepertoire = 9,
                            ShowTime = new TimeOnly(18, 24, 34, 475).Add(TimeSpan.FromTicks(8871))
                        },
                        new
                        {
                            IdMovieRepertoire = 35,
                            IdMovie = 7,
                            IdRepertoire = 9,
                            ShowTime = new TimeOnly(19, 24, 34, 475).Add(TimeSpan.FromTicks(8873))
                        },
                        new
                        {
                            IdMovieRepertoire = 36,
                            IdMovie = 1,
                            IdRepertoire = 9,
                            ShowTime = new TimeOnly(20, 24, 34, 475).Add(TimeSpan.FromTicks(8875))
                        },
                        new
                        {
                            IdMovieRepertoire = 37,
                            IdMovie = 2,
                            IdRepertoire = 10,
                            ShowTime = new TimeOnly(17, 24, 34, 475).Add(TimeSpan.FromTicks(8877))
                        },
                        new
                        {
                            IdMovieRepertoire = 38,
                            IdMovie = 3,
                            IdRepertoire = 10,
                            ShowTime = new TimeOnly(18, 24, 34, 475).Add(TimeSpan.FromTicks(8879))
                        },
                        new
                        {
                            IdMovieRepertoire = 39,
                            IdMovie = 4,
                            IdRepertoire = 10,
                            ShowTime = new TimeOnly(19, 24, 34, 475).Add(TimeSpan.FromTicks(8881))
                        },
                        new
                        {
                            IdMovieRepertoire = 40,
                            IdMovie = 5,
                            IdRepertoire = 10,
                            ShowTime = new TimeOnly(20, 24, 34, 475).Add(TimeSpan.FromTicks(8883))
                        },
                        new
                        {
                            IdMovieRepertoire = 41,
                            IdMovie = 6,
                            IdRepertoire = 11,
                            ShowTime = new TimeOnly(17, 24, 34, 475).Add(TimeSpan.FromTicks(8885))
                        },
                        new
                        {
                            IdMovieRepertoire = 42,
                            IdMovie = 7,
                            IdRepertoire = 11,
                            ShowTime = new TimeOnly(18, 24, 34, 475).Add(TimeSpan.FromTicks(8887))
                        },
                        new
                        {
                            IdMovieRepertoire = 43,
                            IdMovie = 8,
                            IdRepertoire = 11,
                            ShowTime = new TimeOnly(19, 24, 34, 475).Add(TimeSpan.FromTicks(8889))
                        },
                        new
                        {
                            IdMovieRepertoire = 44,
                            IdMovie = 9,
                            IdRepertoire = 11,
                            ShowTime = new TimeOnly(20, 24, 34, 475).Add(TimeSpan.FromTicks(8890))
                        },
                        new
                        {
                            IdMovieRepertoire = 45,
                            IdMovie = 10,
                            IdRepertoire = 12,
                            ShowTime = new TimeOnly(17, 24, 34, 475).Add(TimeSpan.FromTicks(8892))
                        },
                        new
                        {
                            IdMovieRepertoire = 46,
                            IdMovie = 11,
                            IdRepertoire = 12,
                            ShowTime = new TimeOnly(18, 24, 34, 475).Add(TimeSpan.FromTicks(8894))
                        },
                        new
                        {
                            IdMovieRepertoire = 47,
                            IdMovie = 12,
                            IdRepertoire = 12,
                            ShowTime = new TimeOnly(19, 24, 34, 475).Add(TimeSpan.FromTicks(8896))
                        },
                        new
                        {
                            IdMovieRepertoire = 48,
                            IdMovie = 13,
                            IdRepertoire = 12,
                            ShowTime = new TimeOnly(20, 24, 34, 475).Add(TimeSpan.FromTicks(8898))
                        },
                        new
                        {
                            IdMovieRepertoire = 49,
                            IdMovie = 14,
                            IdRepertoire = 13,
                            ShowTime = new TimeOnly(17, 24, 34, 475).Add(TimeSpan.FromTicks(8900))
                        },
                        new
                        {
                            IdMovieRepertoire = 50,
                            IdMovie = 15,
                            IdRepertoire = 13,
                            ShowTime = new TimeOnly(18, 24, 34, 475).Add(TimeSpan.FromTicks(8902))
                        },
                        new
                        {
                            IdMovieRepertoire = 51,
                            IdMovie = 16,
                            IdRepertoire = 13,
                            ShowTime = new TimeOnly(19, 24, 34, 475).Add(TimeSpan.FromTicks(8904))
                        },
                        new
                        {
                            IdMovieRepertoire = 52,
                            IdMovie = 17,
                            IdRepertoire = 13,
                            ShowTime = new TimeOnly(20, 24, 34, 475).Add(TimeSpan.FromTicks(8906))
                        },
                        new
                        {
                            IdMovieRepertoire = 53,
                            IdMovie = 18,
                            IdRepertoire = 14,
                            ShowTime = new TimeOnly(17, 24, 34, 475).Add(TimeSpan.FromTicks(8908))
                        },
                        new
                        {
                            IdMovieRepertoire = 54,
                            IdMovie = 19,
                            IdRepertoire = 14,
                            ShowTime = new TimeOnly(18, 24, 34, 475).Add(TimeSpan.FromTicks(8910))
                        },
                        new
                        {
                            IdMovieRepertoire = 55,
                            IdMovie = 20,
                            IdRepertoire = 14,
                            ShowTime = new TimeOnly(19, 24, 34, 475).Add(TimeSpan.FromTicks(8912))
                        },
                        new
                        {
                            IdMovieRepertoire = 56,
                            IdMovie = 1,
                            IdRepertoire = 14,
                            ShowTime = new TimeOnly(20, 24, 34, 475).Add(TimeSpan.FromTicks(8914))
                        },
                        new
                        {
                            IdMovieRepertoire = 57,
                            IdMovie = 2,
                            IdRepertoire = 15,
                            ShowTime = new TimeOnly(17, 24, 34, 475).Add(TimeSpan.FromTicks(8916))
                        },
                        new
                        {
                            IdMovieRepertoire = 58,
                            IdMovie = 3,
                            IdRepertoire = 15,
                            ShowTime = new TimeOnly(18, 24, 34, 475).Add(TimeSpan.FromTicks(8917))
                        },
                        new
                        {
                            IdMovieRepertoire = 59,
                            IdMovie = 4,
                            IdRepertoire = 15,
                            ShowTime = new TimeOnly(19, 24, 34, 475).Add(TimeSpan.FromTicks(8919))
                        },
                        new
                        {
                            IdMovieRepertoire = 60,
                            IdMovie = 5,
                            IdRepertoire = 15,
                            ShowTime = new TimeOnly(20, 24, 34, 475).Add(TimeSpan.FromTicks(8921))
                        },
                        new
                        {
                            IdMovieRepertoire = 61,
                            IdMovie = 6,
                            IdRepertoire = 16,
                            ShowTime = new TimeOnly(17, 24, 34, 475).Add(TimeSpan.FromTicks(8923))
                        },
                        new
                        {
                            IdMovieRepertoire = 62,
                            IdMovie = 7,
                            IdRepertoire = 16,
                            ShowTime = new TimeOnly(18, 24, 34, 475).Add(TimeSpan.FromTicks(8925))
                        },
                        new
                        {
                            IdMovieRepertoire = 63,
                            IdMovie = 8,
                            IdRepertoire = 16,
                            ShowTime = new TimeOnly(19, 24, 34, 475).Add(TimeSpan.FromTicks(8927))
                        },
                        new
                        {
                            IdMovieRepertoire = 64,
                            IdMovie = 9,
                            IdRepertoire = 16,
                            ShowTime = new TimeOnly(20, 24, 34, 475).Add(TimeSpan.FromTicks(8929))
                        },
                        new
                        {
                            IdMovieRepertoire = 65,
                            IdMovie = 10,
                            IdRepertoire = 17,
                            ShowTime = new TimeOnly(17, 24, 34, 475).Add(TimeSpan.FromTicks(8931))
                        },
                        new
                        {
                            IdMovieRepertoire = 66,
                            IdMovie = 11,
                            IdRepertoire = 17,
                            ShowTime = new TimeOnly(18, 24, 34, 475).Add(TimeSpan.FromTicks(8933))
                        },
                        new
                        {
                            IdMovieRepertoire = 67,
                            IdMovie = 12,
                            IdRepertoire = 17,
                            ShowTime = new TimeOnly(19, 24, 34, 475).Add(TimeSpan.FromTicks(8935))
                        },
                        new
                        {
                            IdMovieRepertoire = 68,
                            IdMovie = 13,
                            IdRepertoire = 17,
                            ShowTime = new TimeOnly(20, 24, 34, 475).Add(TimeSpan.FromTicks(8937))
                        },
                        new
                        {
                            IdMovieRepertoire = 69,
                            IdMovie = 14,
                            IdRepertoire = 18,
                            ShowTime = new TimeOnly(17, 24, 34, 475).Add(TimeSpan.FromTicks(8938))
                        },
                        new
                        {
                            IdMovieRepertoire = 70,
                            IdMovie = 15,
                            IdRepertoire = 18,
                            ShowTime = new TimeOnly(18, 24, 34, 475).Add(TimeSpan.FromTicks(8940))
                        },
                        new
                        {
                            IdMovieRepertoire = 71,
                            IdMovie = 16,
                            IdRepertoire = 19,
                            ShowTime = new TimeOnly(18, 24, 34, 475).Add(TimeSpan.FromTicks(8942))
                        },
                        new
                        {
                            IdMovieRepertoire = 72,
                            IdMovie = 17,
                            IdRepertoire = 19,
                            ShowTime = new TimeOnly(19, 24, 34, 475).Add(TimeSpan.FromTicks(8944))
                        },
                        new
                        {
                            IdMovieRepertoire = 73,
                            IdMovie = 18,
                            IdRepertoire = 20,
                            ShowTime = new TimeOnly(20, 24, 34, 475).Add(TimeSpan.FromTicks(8946))
                        },
                        new
                        {
                            IdMovieRepertoire = 74,
                            IdMovie = 19,
                            IdRepertoire = 20,
                            ShowTime = new TimeOnly(17, 24, 34, 475).Add(TimeSpan.FromTicks(8948))
                        },
                        new
                        {
                            IdMovieRepertoire = 75,
                            IdMovie = 20,
                            IdRepertoire = 21,
                            ShowTime = new TimeOnly(18, 24, 34, 475).Add(TimeSpan.FromTicks(8950))
                        },
                        new
                        {
                            IdMovieRepertoire = 76,
                            IdMovie = 1,
                            IdRepertoire = 21,
                            ShowTime = new TimeOnly(19, 24, 34, 475).Add(TimeSpan.FromTicks(8952))
                        },
                        new
                        {
                            IdMovieRepertoire = 77,
                            IdMovie = 2,
                            IdRepertoire = 22,
                            ShowTime = new TimeOnly(20, 24, 34, 475).Add(TimeSpan.FromTicks(8954))
                        },
                        new
                        {
                            IdMovieRepertoire = 78,
                            IdMovie = 3,
                            IdRepertoire = 22,
                            ShowTime = new TimeOnly(17, 24, 34, 475).Add(TimeSpan.FromTicks(8956))
                        },
                        new
                        {
                            IdMovieRepertoire = 79,
                            IdMovie = 4,
                            IdRepertoire = 23,
                            ShowTime = new TimeOnly(18, 24, 34, 475).Add(TimeSpan.FromTicks(8958))
                        },
                        new
                        {
                            IdMovieRepertoire = 80,
                            IdMovie = 5,
                            IdRepertoire = 23,
                            ShowTime = new TimeOnly(19, 24, 34, 475).Add(TimeSpan.FromTicks(8960))
                        },
                        new
                        {
                            IdMovieRepertoire = 81,
                            IdMovie = 6,
                            IdRepertoire = 24,
                            ShowTime = new TimeOnly(20, 24, 34, 475).Add(TimeSpan.FromTicks(8962))
                        },
                        new
                        {
                            IdMovieRepertoire = 82,
                            IdMovie = 7,
                            IdRepertoire = 24,
                            ShowTime = new TimeOnly(17, 24, 34, 475).Add(TimeSpan.FromTicks(8963))
                        },
                        new
                        {
                            IdMovieRepertoire = 83,
                            IdMovie = 8,
                            IdRepertoire = 25,
                            ShowTime = new TimeOnly(18, 24, 34, 475).Add(TimeSpan.FromTicks(8965))
                        },
                        new
                        {
                            IdMovieRepertoire = 84,
                            IdMovie = 9,
                            IdRepertoire = 25,
                            ShowTime = new TimeOnly(19, 24, 34, 475).Add(TimeSpan.FromTicks(8967))
                        },
                        new
                        {
                            IdMovieRepertoire = 85,
                            IdMovie = 10,
                            IdRepertoire = 26,
                            ShowTime = new TimeOnly(20, 24, 34, 475).Add(TimeSpan.FromTicks(8969))
                        },
                        new
                        {
                            IdMovieRepertoire = 86,
                            IdMovie = 11,
                            IdRepertoire = 26,
                            ShowTime = new TimeOnly(17, 24, 34, 475).Add(TimeSpan.FromTicks(8971))
                        },
                        new
                        {
                            IdMovieRepertoire = 87,
                            IdMovie = 12,
                            IdRepertoire = 27,
                            ShowTime = new TimeOnly(18, 24, 34, 475).Add(TimeSpan.FromTicks(8973))
                        },
                        new
                        {
                            IdMovieRepertoire = 88,
                            IdMovie = 13,
                            IdRepertoire = 27,
                            ShowTime = new TimeOnly(19, 24, 34, 475).Add(TimeSpan.FromTicks(8975))
                        },
                        new
                        {
                            IdMovieRepertoire = 89,
                            IdMovie = 14,
                            IdRepertoire = 28,
                            ShowTime = new TimeOnly(20, 24, 34, 475).Add(TimeSpan.FromTicks(8977))
                        },
                        new
                        {
                            IdMovieRepertoire = 90,
                            IdMovie = 15,
                            IdRepertoire = 28,
                            ShowTime = new TimeOnly(17, 24, 34, 475).Add(TimeSpan.FromTicks(8979))
                        },
                        new
                        {
                            IdMovieRepertoire = 91,
                            IdMovie = 16,
                            IdRepertoire = 29,
                            ShowTime = new TimeOnly(18, 24, 34, 475).Add(TimeSpan.FromTicks(8981))
                        },
                        new
                        {
                            IdMovieRepertoire = 92,
                            IdMovie = 17,
                            IdRepertoire = 29,
                            ShowTime = new TimeOnly(19, 24, 34, 475).Add(TimeSpan.FromTicks(8983))
                        },
                        new
                        {
                            IdMovieRepertoire = 93,
                            IdMovie = 18,
                            IdRepertoire = 30,
                            ShowTime = new TimeOnly(20, 24, 34, 475).Add(TimeSpan.FromTicks(8985))
                        },
                        new
                        {
                            IdMovieRepertoire = 94,
                            IdMovie = 19,
                            IdRepertoire = 30,
                            ShowTime = new TimeOnly(17, 24, 34, 475).Add(TimeSpan.FromTicks(8986))
                        });
                });

            modelBuilder.Entity("TIN_Project.Server.Models.Order", b =>
                {
                    b.Property<int>("IdUser")
                        .HasColumnType("INTEGER");

                    b.Property<int>("IdMovieRepertoire")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsPaid")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdUser", "IdMovieRepertoire");

                    b.HasIndex("IdMovieRepertoire");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            IdUser = 2,
                            IdMovieRepertoire = 7,
                            IsPaid = true
                        },
                        new
                        {
                            IdUser = 2,
                            IdMovieRepertoire = 8,
                            IsPaid = false
                        },
                        new
                        {
                            IdUser = 2,
                            IdMovieRepertoire = 9,
                            IsPaid = true
                        },
                        new
                        {
                            IdUser = 2,
                            IdMovieRepertoire = 10,
                            IsPaid = false
                        },
                        new
                        {
                            IdUser = 2,
                            IdMovieRepertoire = 11,
                            IsPaid = true
                        },
                        new
                        {
                            IdUser = 2,
                            IdMovieRepertoire = 12,
                            IsPaid = false
                        });
                });

            modelBuilder.Entity("TIN_Project.Server.Models.Repertoire", b =>
                {
                    b.Property<int>("IdRepertoire")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("TEXT");

                    b.Property<int>("IdCinema")
                        .HasColumnType("INTEGER");

                    b.HasKey("IdRepertoire");

                    b.HasIndex("IdCinema");

                    b.ToTable("Repertoires");

                    b.HasData(
                        new
                        {
                            IdRepertoire = 1,
                            Date = new DateOnly(2024, 1, 15),
                            IdCinema = 1
                        },
                        new
                        {
                            IdRepertoire = 2,
                            Date = new DateOnly(2024, 1, 16),
                            IdCinema = 1
                        },
                        new
                        {
                            IdRepertoire = 3,
                            Date = new DateOnly(2024, 1, 17),
                            IdCinema = 1
                        },
                        new
                        {
                            IdRepertoire = 4,
                            Date = new DateOnly(2024, 1, 18),
                            IdCinema = 1
                        },
                        new
                        {
                            IdRepertoire = 5,
                            Date = new DateOnly(2024, 1, 19),
                            IdCinema = 1
                        },
                        new
                        {
                            IdRepertoire = 6,
                            Date = new DateOnly(2024, 1, 15),
                            IdCinema = 2
                        },
                        new
                        {
                            IdRepertoire = 7,
                            Date = new DateOnly(2024, 1, 16),
                            IdCinema = 2
                        },
                        new
                        {
                            IdRepertoire = 8,
                            Date = new DateOnly(2024, 1, 17),
                            IdCinema = 2
                        },
                        new
                        {
                            IdRepertoire = 9,
                            Date = new DateOnly(2024, 1, 18),
                            IdCinema = 2
                        },
                        new
                        {
                            IdRepertoire = 10,
                            Date = new DateOnly(2024, 1, 19),
                            IdCinema = 2
                        },
                        new
                        {
                            IdRepertoire = 11,
                            Date = new DateOnly(2024, 1, 15),
                            IdCinema = 3
                        },
                        new
                        {
                            IdRepertoire = 12,
                            Date = new DateOnly(2024, 1, 16),
                            IdCinema = 3
                        },
                        new
                        {
                            IdRepertoire = 13,
                            Date = new DateOnly(2024, 1, 17),
                            IdCinema = 3
                        },
                        new
                        {
                            IdRepertoire = 14,
                            Date = new DateOnly(2024, 1, 18),
                            IdCinema = 3
                        },
                        new
                        {
                            IdRepertoire = 15,
                            Date = new DateOnly(2024, 1, 19),
                            IdCinema = 3
                        },
                        new
                        {
                            IdRepertoire = 16,
                            Date = new DateOnly(2024, 1, 15),
                            IdCinema = 4
                        },
                        new
                        {
                            IdRepertoire = 17,
                            Date = new DateOnly(2024, 1, 16),
                            IdCinema = 4
                        },
                        new
                        {
                            IdRepertoire = 18,
                            Date = new DateOnly(2024, 1, 17),
                            IdCinema = 4
                        },
                        new
                        {
                            IdRepertoire = 19,
                            Date = new DateOnly(2024, 1, 18),
                            IdCinema = 4
                        },
                        new
                        {
                            IdRepertoire = 20,
                            Date = new DateOnly(2024, 1, 19),
                            IdCinema = 4
                        },
                        new
                        {
                            IdRepertoire = 21,
                            Date = new DateOnly(2024, 1, 15),
                            IdCinema = 5
                        },
                        new
                        {
                            IdRepertoire = 22,
                            Date = new DateOnly(2024, 1, 16),
                            IdCinema = 5
                        },
                        new
                        {
                            IdRepertoire = 23,
                            Date = new DateOnly(2024, 1, 17),
                            IdCinema = 5
                        },
                        new
                        {
                            IdRepertoire = 24,
                            Date = new DateOnly(2024, 1, 18),
                            IdCinema = 5
                        },
                        new
                        {
                            IdRepertoire = 25,
                            Date = new DateOnly(2024, 1, 19),
                            IdCinema = 5
                        },
                        new
                        {
                            IdRepertoire = 26,
                            Date = new DateOnly(2024, 1, 15),
                            IdCinema = 6
                        },
                        new
                        {
                            IdRepertoire = 27,
                            Date = new DateOnly(2024, 1, 16),
                            IdCinema = 6
                        },
                        new
                        {
                            IdRepertoire = 28,
                            Date = new DateOnly(2024, 1, 17),
                            IdCinema = 6
                        },
                        new
                        {
                            IdRepertoire = 29,
                            Date = new DateOnly(2024, 1, 18),
                            IdCinema = 6
                        },
                        new
                        {
                            IdRepertoire = 30,
                            Date = new DateOnly(2024, 1, 19),
                            IdCinema = 6
                        });
                });

            modelBuilder.Entity("TIN_Project.Server.Models.User", b =>
                {
                    b.Property<int>("IdUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("BirthDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("RefreshTokenExpirationDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("Role")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("TEXT");

                    b.HasKey("IdUser");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            IdUser = 1,
                            BirthDate = new DateOnly(2000, 1, 1),
                            Email = "superuser@superuser.com",
                            Name = "Superuser",
                            Password = "password",
                            Role = 0,
                            Surname = "Superuser",
                            Username = "superuser"
                        },
                        new
                        {
                            IdUser = 2,
                            BirthDate = new DateOnly(1999, 1, 1),
                            Email = "johndoe@doe.com",
                            Name = "John",
                            Password = "password",
                            Role = 2,
                            Surname = "Doe",
                            Username = "username"
                        },
                        new
                        {
                            IdUser = 3,
                            BirthDate = new DateOnly(2000, 1, 1),
                            Email = "admin@admin.com",
                            Name = "Admin",
                            Password = "password",
                            Role = 1,
                            Surname = "Admin",
                            Username = "admin"
                        });
                });

            modelBuilder.Entity("GenreMovie", b =>
                {
                    b.HasOne("TIN_Project.Server.Models.Genre", null)
                        .WithMany()
                        .HasForeignKey("GenresIdGenre")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TIN_Project.Server.Models.Movie", null)
                        .WithMany()
                        .HasForeignKey("MoviesIdMovie")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TIN_Project.Server.Models.MovieRepertoire", b =>
                {
                    b.HasOne("TIN_Project.Server.Models.Movie", "Movie")
                        .WithMany("MovieRepertoires")
                        .HasForeignKey("IdMovie")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TIN_Project.Server.Models.Repertoire", "Repertoire")
                        .WithMany("MovieRepertoires")
                        .HasForeignKey("IdRepertoire")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("Repertoire");
                });

            modelBuilder.Entity("TIN_Project.Server.Models.Order", b =>
                {
                    b.HasOne("TIN_Project.Server.Models.MovieRepertoire", "MovieRepertoire")
                        .WithMany("Orders")
                        .HasForeignKey("IdMovieRepertoire")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TIN_Project.Server.Models.User", "User")
                        .WithMany("Orders")
                        .HasForeignKey("IdUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MovieRepertoire");

                    b.Navigation("User");
                });

            modelBuilder.Entity("TIN_Project.Server.Models.Repertoire", b =>
                {
                    b.HasOne("TIN_Project.Server.Models.Cinema", "Cinema")
                        .WithMany("Repertoires")
                        .HasForeignKey("IdCinema")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cinema");
                });

            modelBuilder.Entity("TIN_Project.Server.Models.Cinema", b =>
                {
                    b.Navigation("Repertoires");
                });

            modelBuilder.Entity("TIN_Project.Server.Models.Movie", b =>
                {
                    b.Navigation("MovieRepertoires");
                });

            modelBuilder.Entity("TIN_Project.Server.Models.MovieRepertoire", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("TIN_Project.Server.Models.Repertoire", b =>
                {
                    b.Navigation("MovieRepertoires");
                });

            modelBuilder.Entity("TIN_Project.Server.Models.User", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
